# Generated by Django 3.1 on 2020-10-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('nom', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nom')),
                ('type_contenant', models.CharField(blank=True, max_length=9, verbose_name='Type de contenant')),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
            },
        ),
        migrations.CreateModel(
            name='Graine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_graine', models.CharField(blank=True, max_length=50, verbose_name='Type')),
                ('espece_graine', models.CharField(blank=True, max_length=50, verbose_name='Espèce')),
                ('variete_graine', models.CharField(blank=True, max_length=50, verbose_name='Variété')),
                ('niveau_stock', models.CharField(blank=True, max_length=8, verbose_name='Niveau du stock')),
                ('provenance', models.CharField(blank=True, max_length=50, verbose_name='Provenance')),
                ('annee_recolte', models.CharField(blank=True, max_length=4, verbose_name='Année de récolte')),
                ('remarques', models.CharField(blank=True, max_length=150, verbose_name='Remarques')),
                ('nom_usuel', models.CharField(blank=True, max_length=50, verbose_name='Plante')),
            ],
            options={
                'verbose_name': 'Graine',
                'verbose_name_plural': 'Graines',
            },
        ),
        migrations.CreateModel(
            name='PhaseCulture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=7, verbose_name='Phase')),
                ('phase_date', models.DateField(verbose_name='Date de changement de phase')),
                ('nom_culture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phase_culture_nom_culture', to='Sensorialys_django_app.culture', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'Phase de culture',
                'verbose_name_plural': 'Phases de culture',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_culture_initial', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom de culture initial')),
                ('quantite_lot', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('id_graine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etat_lot_id_graine', to='Sensorialys_django_app.graine', verbose_name='Graine')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
            },
        ),
        migrations.CreateModel(
            name='EtatLot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(blank=True, max_length=50, null=True, verbose_name='État')),
                ('date', models.DateField(blank=True, null=True, verbose_name="Date de l'état")),
                ('phase_lunaire', models.CharField(blank=True, max_length=4, verbose_name='Phase lunaire')),
                ('constellation', models.CharField(blank=True, max_length=7, verbose_name='Constellation')),
                ('quantite', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('quantite_etat', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantité relatée')),
                ('remarques', models.CharField(blank=True, max_length=150, verbose_name='Remarques')),
                ('id_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etat_lot_id_lot', to='Sensorialys_django_app.lot', verbose_name='Lot')),
                ('nom_culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etat_lot_nom_culture', to='Sensorialys_django_app.culture', verbose_name='Culture')),
            ],
            options={
                'verbose_name': 'État du lot',
                'verbose_name_plural': 'États du lot',
            },
        ),
    ]
