# Generated by Django 3.1 on 2020-10-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='niveau_stock',
            field=models.CharField(blank=True, max_length=50, verbose_name='Niveau du stock'),
        ),
    ]
