# Generated by Django 3.1 on 2020-10-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0002_auto_20201017_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='annee_recolte',
            field=models.CharField(blank=True, max_length=50, verbose_name='Année de récolte'),
        ),
    ]
