# Generated by Django 3.1 on 2020-10-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0003_auto_20201017_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='annee_recolte',
            field=models.CharField(blank=True, max_length=6, verbose_name='Année de récolte'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='niveau_stock',
            field=models.CharField(blank=True, max_length=8, verbose_name='Niveau du stock'),
        ),
    ]
