# Generated by Django 3.1 on 2020-10-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0004_auto_20201017_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='remarques',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarques'),
        ),
    ]
