# Generated by Django 3.1 on 2020-10-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0005_auto_20201017_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graine',
            name='niveau_stock',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Niveau du stock'),
        ),
    ]
