# Generated by Django 3.1 on 2020-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0006_auto_20201017_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='type_contenant',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Type de contenant'),
        ),
        migrations.AlterField(
            model_name='etatlot',
            name='constellation',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Constellation'),
        ),
        migrations.AlterField(
            model_name='etatlot',
            name='phase_lunaire',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Phase lunaire'),
        ),
        migrations.AlterField(
            model_name='etatlot',
            name='remarques',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='annee_recolte',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Année de récolte'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='espece_graine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='nom_usuel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Plante'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='provenance',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provenance'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='type_graine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='variete_graine',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Variété'),
        ),
        migrations.AlterField(
            model_name='phaseculture',
            name='phase',
            field=models.CharField(max_length=7, null=True, verbose_name='Phase'),
        ),
    ]
