# Generated by Django 3.1 on 2020-10-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0007_auto_20201017_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='etatlot',
            name='lunar_node',
            field=models.BooleanField(blank=True, null=True, verbose_name='Noeud lunaire'),
        ),
        migrations.AddField(
            model_name='etatlot',
            name='perigee_apogee',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Périgée / Apogée'),
        ),
        migrations.AlterField(
            model_name='graine',
            name='annee_recolte',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Année de récolte'),
        ),
    ]
