# Generated by Django 3.1 on 2020-10-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sensorialys_django_app', '0008_auto_20201026_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etatlot',
            name='lunar_node',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Noeud lunaire'),
        ),
    ]
